# Generated by Django 3.1.3 on 2020-11-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('major', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=500)),
                ('gpa', models.DecimalField(decimal_places=1, max_digits=3)),
                ('courseid', models.IntegerField()),
                ('coursetitle', models.CharField(max_length=500)),
                ('coursename', models.CharField(max_length=500)),
                ('coursesectioncode', models.IntegerField()),
                ('coursedepartment', models.CharField(max_length=500)),
            ],
        ),
    ]
